-- Learning-flow extension: identities, guest sessions and live-room admission.
-- Apply after 202608070001_exam_schema.sql.

create type public.app_role as enum ('student', 'teacher');
create type public.room_participant_status as enum (
  'waiting', 'late_join_requested', 'approved', 'rejected', 'left'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  active_role public.app_role not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (display_name is null or char_length(trim(display_name)) between 2 and 80)
);

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger auth_user_creates_profile
after insert on auth.users for each row execute function public.create_profile_for_new_user();

alter table public.profiles enable row level security;
create policy "users read own profile" on public.profiles for select using (id = auth.uid());
create policy "users update own profile" on public.profiles for update
  using (id = auth.uid()) with check (id = auth.uid());

-- A random secret, generated by the client and returned only once by the RPC,
-- identifies a guest's attempt. Only its bcrypt hash is stored.
alter table public.attempts
  add column guest_access_token_hash text,
  add column expires_at timestamptz,
  add column result_released_at timestamptz;

alter table public.attempts
  add constraint attempts_guest_token_required
  check (user_id is not null or guest_access_token_hash is not null);

create table public.exam_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  exam_id uuid not null references public.exams(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, exam_id)
);

alter table public.exam_favorites enable row level security;
create policy "users manage own favorites" on public.exam_favorites
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create table public.room_participants (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  guest_name text,
  guest_access_token_hash text,
  status public.room_participant_status not null default 'waiting',
  requested_at timestamptz not null default now(),
  approved_at timestamptz,
  attempt_id uuid unique references public.attempts(id) on delete set null,
  last_seen_at timestamptz not null default now(),
  check (user_id is not null or (guest_name is not null and guest_access_token_hash is not null)),
  check ((status = 'approved') = (approved_at is not null))
);

create unique index room_participants_one_user_per_room
  on public.room_participants(room_id, user_id) where user_id is not null;
create index room_participants_room_status_index
  on public.room_participants(room_id, status, requested_at);

alter table public.room_participants enable row level security;
-- The client accesses participant state only through RPCs; teachers get the
-- intentionally limited dashboard payload from a server function.

-- Keep the original exam immutable once somebody begins it.
create or replace function public.prevent_mutating_started_exam()
returns trigger language plpgsql set search_path = public as $$
begin
  if exists (select 1 from public.attempts where exam_id = old.id) then
    raise exception 'An exam with attempts cannot be changed; duplicate it first.';
  end if;
  return new;
end;
$$;

create trigger exams_are_immutable_after_first_attempt
before update or delete on public.exams
for each row execute function public.prevent_mutating_started_exam();

-- Used by server-side RPCs and Edge Functions to identify the owning teacher.
create or replace function public.current_teacher_id()
returns uuid language plpgsql security definer set search_path = public as $$
declare
  teacher_id uuid;
begin
  select id into teacher_id from public.teachers where owner_user_id = auth.uid();
  return teacher_id;
end;
$$;

-- Realtime is deliberately restricted to non-sensitive room state. Do not add
-- questions, options, attempts, or answer rows to this publication.
alter publication supabase_realtime add table public.rooms, public.room_participants;

